post http://localhost:3000/v1/teacher
Content-Type: application/json

{
  "firstname": "Silvia",
  "lastname": "Nishimura",
  "age": 28,
  "gender": "F",
  "email": "silvia.nishimuraemail.com",
  "urlProfile": "https://www.linkedin.com/in/silvianishimura"
}

###
get http://localhost:3000/v1/teacher

###
get http://localhost:3000/teacher/2

###
put http://localhost:3000/teacher/2
Content-Type: application/json

{
    "firstname": "Jimena"
}

###
get http://localhost:3000/teacher/page/?page=1&pageSize=2

###
delete http://localhost:3000/teacher/2