post http://development.eba-f6egwrna.us-east-1.elasticbeanstalk.com/v1/user
Content-Type: application/json

{
  "firstname": "Hector",
  "lastname": "Barrionuevo",
  "email": "hector.barrionuevo@email.com",
  "password": "Elgigante2025",
  "roles": [{"id": 1}, {"id": 2}]
}

###
get http://development.eba-f6egwrna.us-east-1.elasticbeanstalk.com/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOiJIZWN0b3IiLCJsYXN0bmFtZSI6IkJhcnJpb251ZXZvIiwicm9sZXMiOlt7ImlkIjoxLCJuYW1lIjoiQURNSU4ifSx7ImlkIjoyLCJuYW1lIjoiT1BFUkFUT1IifV0sImlhdCI6MTczNTQ5Nzg3NiwiZXhwIjoxNzM1NDk5Njc2fQ.Jer6KiZA7zIS6X2xCPaS82v5CfkX3xbhrPw3Ry7qBOU

###
get http://localhost:3000/v1/user/8

###
put http://localhost:3000/v1/user/0
Content-Type: application/json

{
    "email": "prueba@email.com"
}

###
get http://localhost:3000/v1/user/page/?page=1&pageSize=2

###
delete http://localhost:3000/user/2